<?php 
echo $this->helper('Trenza\Themeoption\Helper\Data')->getConfig('option_section/general/background_color');

//$helper = $this->objectManager->create('Trenza\Themeoption\Helper\Data');
//echo $helper->getGeneralConfig('background_color');
        //create block_identifier static block
       // echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_identifier')->toHtml();?>

<?php echo __('custom block.'); ?>